remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Custom Bulma variables
sass:
  style: compressed
  sass_dir: _sass

include:
  - index.md
  - projects.md